{
  "name": "gulp-graceful-error",
  "version": "1.1.1",
  "description": "allow failing tasks to continue the build while still failing",
  "main": "lib/index.js",
  "scripts": {
    "test": "mocha",
    "coverage": "istanbul cover --hook-run-in-context --dir coverage node_modules/mocha/bin/_mocha"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/catdad/gulp-graceful-error.git"
  },
  "author": "Kiril Vatev <vatev.1@gmail.com>",
  "license": "ISC",
  "bugs": {
    "url": "https://github.com/catdad/gulp-graceful-error/issues"
  },
  "homepage": "https://github.com/catdad/gulp-graceful-error#readme",
  "devDependencies": {
    "chai": "^3.5.0",
    "codeclimate-test-reporter": "^0.4.0",
    "istanbul": "^0.4.5",
    "mocha": "^3.2.0",
    "unstyle": "0.0.8"
  },
  "dependencies": {
    "fancy-log": "^1.3.2",
    "plugin-error": "^1.0.0",
    "through2": "^2.0.3"
  },
  "keywords": [
    "gulpplugin",
    "gulp",
    "error",
    "errorhandle",
    "graceful"
  ]
}
